tutorial/src/tutorial/api/v1/sales/urls.py
from django.conf.urls import url,include
import views

urlpatterns = [
	url(r'^$', views.sales, name='sales'),
	url(r'^view/(?P<pk>.*)/$', views.sale, name='sale'),
]

tutorial/src/tutorial/sales/urls.py
from django.conf.urls import url,include
import views


urlpatterns = [
    url(r'^create/$', views.create, name='create'),
    url(r'^edit/(?P<pk>.*)/$', views.edit, name='edit'),
    url(r'^$', views.sales, name='sales'),
    url(r'^view/(?P<pk>.*)/$', views.sale, name='sale'),
    url(r'^delete/(?P<pk>.*)/$', views.delete, name='delete'),
]

tutorial/src/tutorial/tutorial/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from main import views as general_views
from django.conf import settings
from registration.backends.default.views import RegistrationView
from users.forms import RegForm
from users.backend import user_created
from django.views.static import serve


urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^api-auth/', include('rest_framework.urls')),
    url(r'^api/v1/customers/', include('api.v1.customers.urls',namespace="api_v1_customers")),
    url(r'^api/v1/sales/', include('api.v1.sales.urls',namespace="api_v1_sales")),
    url(r'^api/v1/auth/', include('api.v1.authentication.urls',namespace="api_v1_authentication")),

    url(r'^$',general_views.app,name='app'),
    url(r'^app/$',general_views.app,name='app'),
    url(r'^app/dashboard/$',general_views.dashboard,name='dashboard'),

    url(r'^app/customers/', include('customers.urls', namespace="customers")),
    url(r'^app/products/', include('products.urls', namespace="products")),
    url(r'^app/sales/', include('sales.urls', namespace="sales")),

    url(r'^app/accounts/', include('registration.backends.default.urls')),
    url(r'^app/users/', include('users.urls', namespace="users")),

    url(r'^media/(?P<path>.*)$', serve, { 'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve, { 'document_root': settings.STATIC_FILE_ROOT}),
]

tutorial/src/tutorial/sales/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from main.models import BaseModel
from django.utils.translation import ugettext_lazy as _
from django.core.validators import MinValueValidator
from decimal import Decimal


class Sale(BaseModel):
    customer = models.ForeignKey('customers.Customer',limit_choices_to={'is_deleted': False})
    date = models.DateField()
    subtotal = models.DecimalField(default=0.0,decimal_places=2, max_digits=15,validators=[MinValueValidator(Decimal('0.00'))])
    discount = models.DecimalField(default=0.0,decimal_places=2, max_digits=15,validators=[MinValueValidator(Decimal('0.00'))])
    total = models.DecimalField(default=0.0,decimal_places=2, max_digits=15,validators=[MinValueValidator(Decimal('0.00'))])

    class Meta:
        db_table = 'sales_sale'
        verbose_name = _('sale')
        verbose_name_plural = _('sales')
        ordering = ('-date',)

    def __unicode__(self):
        return str(self.auto_id)


class SaleItem(models.Model):
    sale = models.ForeignKey('sales.Sale')
    product = models.ForeignKey('products.Product',limit_choices_to={'is_deleted': False})
    qty = models.DecimalField(default=0.0,decimal_places=2, max_digits=15,validators=[MinValueValidator(Decimal('0.00'))])

    class Meta:
        db_table = 'sales_sale_item'
        verbose_name = _('sale item')
        verbose_name_plural = _('sale items')
        ordering = ('sale',)

    def subtotal(self):
        return (self.qty * self.product.price)

    def __unicode__(self):
        return str(self.sale.auto_id)

tutorial/src/tutorial/sales/forms.py
from django import forms
from django.forms.widgets import TextInput, Textarea, Select
from django.utils.translation import ugettext_lazy as _
from sales.models import Sale, SaleItem
from dal import autocomplete


class SaleForm(forms.ModelForm):
    class Meta:
        model = Sale
        exclude = ['creator','updater','auto_id','is_deleted','subtotal','total']

        widgets = {
            'customer': autocomplete.ModelSelect2(url='customers:customer_autocomplete',attrs={'data-placeholder': 'Customer','data-minimum-input-length': 1},),
                    
            'discount': TextInput(attrs={'class': 'required number form-control','placeholder' : 'Discount'}),
        }

        error_messages = {
            'customer' : {
                'required' : _("Customer field is required."),
            },
            'date' : {
                'required' : _("Date field is required."),
            },
            'discount' : {
                'required' : _("Discount field is required."),
            },
        }


class SaleItemForm(forms.ModelForm):
    class Meta:
        model = SaleItem
        exclude = ['sale']

        widgets = {
            'product': autocomplete.ModelSelect2(url='products:product_autocomplete',attrs={'data-placeholder': 'Product','data-minimum-input-length': 1},),
            'qty': TextInput(attrs={'class': 'required number form-control','placeholder' : 'Qty'}),
        }

        error_messages = {
            'product' : {
                'required' : _("Product field is required."),
            },
            'qty' : {
                'required' : _("Qty field is required."),
            },
        }

tutorial/src/tutorial/api/v1/sales/views.py
from sales.models import Sale
from rest_framework.renderers import JSONRenderer
from rest_framework.decorators import api_view, permission_classes, renderer_classes
from rest_framework.response import Response
from rest_framework.permissions import AllowAny, IsAuthenticated
from api.v1.sales.serializers import SaleSerializer
from rest_framework import status


@api_view(['GET'])
@permission_classes((AllowAny,))
@renderer_classes((JSONRenderer,))
def sales(request):
    instances = Sale.objects.filter(is_deleted=False)
    serialized = SaleSerializer(instances,many=True,context={"request":request})
    
    response_data = {
        "StatusCode" : 6000,
        'data' : serialized.data
    }

    return Response(response_data, status=status.HTTP_200_OK)


@api_view(['GET'])
@permission_classes((AllowAny,))
@renderer_classes((JSONRenderer,))
def sale(request,pk):
    instance = None
    if Sale.objects.filter(is_deleted=False,pk=pk).exists():
        instance = Sale.objects.get(is_deleted=False,pk=pk)

    if instance:
        serialized = SaleSerializer(instance,context={"request":request})
        
        response_data = {
            "StatusCode" : 6000,
            'data' : serialized.data
        }
    else:
        response_data = {
            "StatusCode" : 6001,
            'message' : "Sale not found."
        }

    return Response(response_data, status=status.HTTP_200_OK)

tutorial/src/tutorial/sales/views.py
from django.shortcuts import render, get_object_or_404
from django.http.response import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from main.decorators import check_mode, ajax_required
from main.functions import get_auto_id, generate_form_errors, get_a_id
import json
from django.views.decorators.http import require_GET
from users.models import NotificationSubject, Notification
from django.db.models import Sum, Q
from django.contrib.auth.models import Group
import datetime
from django.utils import timezone
from decimal import Decimal
from sales.models import Sale, SaleItem
from sales.forms import SaleForm, SaleItemForm
from django.forms.models import inlineformset_factory
from django.forms.widgets import TextInput,Select
from django.forms.formsets import formset_factory
from products.functions import update_stock
from products.models import Product
from dal import autocomplete


def create(request): 
    SaleItemFormset = formset_factory(SaleItemForm,extra=1) 
    
    if request.method == 'POST':
        form = SaleForm(request.POST)
        sale_item_formset = SaleItemFormset(request.POST,prefix="sale_item_formset")
        if form.is_valid() and sale_item_formset.is_valid():

            # Creating Sale Item Objects for finding duplicate product entry
            items = {}
            for f in sale_item_formset:  
                product = f.cleaned_data['product']
                qty = f.cleaned_data['qty']
                if str(product.pk) in items:
                    q = items[str(product.pk)]["qty"]
                    items[str(product.pk)]["qty"] = q + qty
                else:
                    dic = {
                        "qty" : qty,
                    }
                    items[str(product.pk)] = dic 

            # Checking the stock available for this product
            stock_ok = True
            error_message = ''
            for key, value in items.iteritems():
                product = Product.objects.get(pk=key)
                stock = product.stock
                qty = value['qty']
                if qty > stock:
                    stock_ok = False
                    error_message += "%s has only %s in stock, You entered %s qty" %(product.name,str(stock),str(qty))

            if stock_ok:
                discount = form.cleaned_data['discount']

                data = form.save(commit=False)
                data.creator = request.user
                data.updater = request.user
                data.auto_id = get_auto_id(Sale)
                data.save()

                subtotal = 0
                for key, value in items.iteritems():
                    product = Product.objects.get(pk=key)
                    qty = value["qty"]
                    price = product.price
                    sub = (qty * price)
                    subtotal += sub 
                    
                    SaleItem(
                        sale = data,
                        product = product,
                        qty = qty
                    ).save()

                    update_stock(product.pk,qty,"decrease")

                total = subtotal - discount

                data.subtotal = subtotal
                data.total = total
                data.save()

                response_data = {
                    "status" : "true",
                    "title" : "Successfully Created",
                    "message" : "Sale Successfully Created.",
                    "redirect" : "true",
                    "redirect_url" : reverse('sales:sale',kwargs={'pk':data.pk})
                } 
            else:
                response_data = {
                    "status" : "false",
                    "stable" : "true",
                    "title" : "Out of Stock",
                    "message" : error_message
                }
        else:
            message = generate_form_errors(form,formset=False)     
            message += generate_form_errors(sale_item_formset,formset=True)
            response_data = {
                "status" : "false",
                "stable" : "true",
                "title" : "Form validation error",
                "message" : message
            }  
            
        return HttpResponse(json.dumps(response_data), content_type='application/javascript')
    else:
        form = SaleForm()
        sale_item_formset = SaleItemFormset(prefix="sale_item_formset")
        context = {
            "title" : "Create Sale",
            "form" : form,
            "sale_item_formset" : sale_item_formset,
            "url" : reverse('sales:create'),
            "redirect" : True,
            "is_create_page" : True,
            
            "is_need_select_picker" : True,
            "is_need_popup_box" : True,
            "is_need_custom_scroll_bar" : True,
            "is_need_wave_effect" : True,
            "is_need_bootstrap_growl" : True,
            "is_need_chosen_select" : True,
            "is_need_grid_system" : True,
            "is_need_datetime_picker" : True,
        }
        return render(request,'sales/entry.html',context)


def edit(request,pk):
    instance = get_object_or_404(Sale.objects.filter(pk=pk,is_deleted=False)) 
    
    if SaleItem.objects.filter(sale=instance).exists():
        extra = 0
    else:
        extra= 1

    SaleItemFormset = inlineformset_factory(
        Sale, 
        SaleItem, 
        can_delete = True,
        extra = extra,
        exclude=('sale',),
        widgets = {
            'product': autocomplete.ModelSelect2(url='products:product_autocomplete',attrs={'data-placeholder': 'Product','data-minimum-input-length': 1},),
            'qty': TextInput(attrs={'class': 'required number form-control','placeholder' : 'Qty'}),
        }
    )
    
    if request.method == 'POST':
        form = SaleForm(request.POST,instance=instance)
        sale_item_formset = SaleItemFormset(request.POST,prefix='sale_item_formset',instance=instance)
        
        if form.is_valid() and sale_item_formset.is_valid():
            
            items = {}

            for f in sale_item_formset:      
                if f not in sale_item_formset.deleted_forms:            
                    product = f.cleaned_data['product']
                    qty = f.cleaned_data['qty']           
                    if str(product.pk) in items:
                        q = items[str(product.pk)]["qty"]
                        items[str(product.pk)]["qty"] = q + qty

                    else:
                        dic = {
                            "qty" : qty
                        }
                        items[str(product.pk)] = dic

            stock_ok = True
            error_message = ''
            for key, value in items.iteritems():
                product = Product.objects.get(pk=key)
                prev_qty = 0
                if SaleItem.objects.filter(sale=instance,product=product).exists():
                    prev_qty = SaleItem.objects.get(sale=instance,product=product).qty                 
                stock = product.stock + prev_qty

                product_qty = value['qty']
                if product_qty > stock:
                    stock_ok = False
                    error_message += "%s has only %s in stock, " %(product.name,str(stock)) 

            if stock_ok:       
                
                #update sale
                discount = form.cleaned_data['discount']

                data = form.save(commit=False)
                data.updator = request.user
                data.date_updated = datetime.datetime.now()
                data.save() 

                all_subtotal = 0
                
                #delete previous items and update stock
                previous_sale_items = SaleItem.objects.filter(sale=instance)
                for p in previous_sale_items: 
                    prev_qty = p.qty                     
                    update_stock(p.product.pk,prev_qty,"increase")         
                previous_sale_items.delete()
                
                #save items
                for key, value in items.iteritems():
                    product = Product.objects.get(pk=key)
                    qty = value["qty"]  
                    price = product.price            
                    subtotal = (qty * price)
                    all_subtotal += subtotal
                    SaleItem(
                        sale = data,
                        product = product,
                        qty = qty,
                    ).save()
                    
                    update_stock(product.pk,qty,"decrease")
                    
                total = all_subtotal - discount

                data.subtotal = all_subtotal
                data.total = total
                data.save()
                
                response_data = {
                    "status" : "true",
                    "title" : "Successfully Updated",
                    "message" : "Sale Successfully Updated.",
                    "redirect" : "true",
                    "redirect_url" : reverse('sales:sale',kwargs={'pk':data.pk})
                }   
            else:
                response_data = {
                    "status" : "false",
                    "stable" : "true",
                    "title" : "Out of Stock",
                    "message" : error_message
                } 
        else:
            message = generate_form_errors(form,formset=False)     
            message += generate_form_errors(sale_item_formset,formset=True)
            response_data = {
                "status" : "false",
                "stable" : "true",
                "title" : "Form validation error",
                "message" : message
            }  
            
        return HttpResponse(json.dumps(response_data), content_type='application/javascript')

    else:        
        form = SaleForm(instance=instance)

tutorial/src/tutorial/templates/sales/sale.html
{% extends "base.html" %}
{% load i18n %}
{% load main_template_tags %}
{% load users_template_tags %}
{% load tz %}
{% block content %}
    <section id="content">
        <div class="container">
            <div class="c-header">
                <h2>{{title}}</h2>
            </div>

            <div class="action-header palette-theme {{current_theme}} bg clearfix">
                <div class="ah-label hidden-xs palette-White text">{{instance.auto_id}} - {{instance.customer}} - {{instance.total}}</div>

                <ul class="ah-actions actions a-alt">
                    <li>
                        <a title="Create Sale" href="{% url 'sales:create' %}">
                            <i class="zmdi zmdi-plus"></i>
                        </a>
                    </li>
                    <li>
                        <a title="Edit Sale" href="{% url 'sales:edit' pk=instance.pk %}">
                            <i class="zmdi zmdi-edit"></i>
                        </a>
                    </li>
                    <li>
                        <a title="Delete Sale" data-id="{{instance.pk}}" data-text="{{confirm_delete_message}}" data-title="Are you sure?" href="{% url 'sales:delete' pk=instance.pk %}" class="action-button redirect">
                            <i class="zmdi zmdi-delete"></i>
                        </a>
                    </li>
                </ul>
            </div>

            <div id="c-grid" class="clearfix" data-columns="2">
                <div class="card">
                    <div class="card-header">
                        <h2>Basic Info <small></small></h2>
                    </div>

                    <div class="card-body">
                        <div class="list-group lg-alt c-overflow">
                            <div class="list-group-item media">
                                <div class="media-body">
                                    <div class="lgi-heading">Customer</div>
                                    <small class="lgi-text">{{instance.customer}}</small>
                                </div>
                            </div>

                            <div class="list-group-item media">
                                <div class="media-body">
                                    <div class="lgi-heading">Date</div>
                                    <small class="lgi-text">{{instance.date|date:"d/m/Y"}}</small>
                                </div>
                            </div>

                            <div class="list-group-item media">
                                <div class="media-body">
                                    <div class="lgi-heading">Subtotal</div>
                                    <small class="lgi-text">{{instance.subtotal}}</small>
                                </div>
                            </div>

                            <div class="list-group-item media">
                                <div class="media-body">
                                    <div class="lgi-heading">Discount</div>
                                    <small class="lgi-text">{{instance.discount}}</small>
                                </div>
                            </div>

                            <div class="list-group-item media">
                                <div class="media-body">
                                    <div class="lgi-heading">Total</div>
                                    <small class="lgi-text">{{instance.total}}</small>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

            {% if sale_items %}
                <div class="card">
                    <div class="card-header">
                        <h2>Items <small></small></h2>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table id="data-table-basic" class="table table-striped table-vmiddle">
                                <thead>
                                    <tr>
                                        <th>Product</th>
                                        <th>Qty</th>
                                        <th>Price</th>
                                        <th>Subtotal</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for i in sale_items %}
                                        <tr>
                                            <td>{{i.product}}</td>
                                            <td>{{i.qty}}</td>
                                            <td>{{i.product.price}}</td>
                                            <td>{{i.subtotal}}</td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            {% endif %}
    </section>
{% endblock %}

{% block static %}
    {% load static %}
{% endblock %}

tutorial/src/tutorial/templates/sales/sales.html
{% extends "base.html" %}
{% load i18n %}


{% block content %}
	<section id="content">
        <div class="container">
             <div class="c-header">
            	<h2>{{title}}</h2>
            </div>

            <div class="action-header palette-theme {{current_theme}} bg clearfix">
	            <div class="ah-label hidden-xs palette-White text">{{title}}</div>

	            <div class="ah-search">
	            	<form method="get" action="{% url 'sales:sales' %}" class="ahs-input">
	                    <input name="q" type="text" placeholder="Start typing..." class="ahs-input">

	                    <i class="ah-search-close zmdi zmdi-long-arrow-left" data-ma-action="ah-search-close"></i>
	                    <input type="submit" class="hidden" />
	                </form>
	            </div>

	            <ul class="ah-actions actions a-alt">
	                <li>
	                    <a href="" class="ah-search-trigger" data-ma-action="ah-search-open">
	                        <i class="zmdi zmdi-search"></i>
	                    </a>
	                </li>
	                <li>
	                    <a title="Filter" class="filter_button" href="">
	                        <i class="zmdi zmdi-filter-list"></i>
	                    </a>
	                </li>
	                <li>
                        <a title="Create Product" href="{% url 'sales:create' %}">
                            <i class="zmdi zmdi-plus"></i>
                        </a>
                    </li>
	                {% if instances %}
    	                <li>
    	                    <a title="Select All" class="check_all" href="">
    	                        <i class="zmdi zmdi-select-all"></i>
    	                    </a>
    	                </li>
	                {% endif %}
	            </ul>
	        </div>

            <div class="card">

				{% if instances %}

                <div class="table-responsive">
                    <table id="data-table-basic" class="table table-striped table-vmiddle">
                        <thead>
                            <tr>
                            	<th style="width:20px;"></th>
                                <th data-column-id="id" data-type="numeric">ID</th>
                                <th>Customer</th>
                                <th>Date</th>
                                <th>Subtotal</th>
                                <th>Discount</th>
                                <th>Total</th>
                                <th data-column-id="action">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                        	{% load el_pagination_tags %}
							{% paginate 21 instances %}
                        	{% for instance in instances %}
                            <tr class="check_items_row">
                            	<td style="width:20px;">
                            		<div class="checkbox lgi-checkbox m-t-5">
			                            <label>
			                                <input class="check check_item" type="checkbox" value="{{instance.pk}}" name="delete_item">
			                                <i class="input-helper"></i>
			                            </label>
			                        </div>
                            	</td>
                                <td><a href="{% url 'sales:sale' pk=instance.pk %}">{{instance.auto_id}}</a></td>
                                <td>{{instance.customer}}</td>
                                <td>{{instance.date}}</td>
                                <td>{{instance.subtotal}}</td>
                                <td>{{instance.discount}}</td>
                                <td>{{instance.total}}</td>
                                <td>
                                	<a href="{% url 'sales:sale' pk=instance.pk %}" class="btn btn-default btn-icon waves-effect waves-circle waves-float"><i class="zmdi zmdi-eye"></i></a>
                                	<a href="{% url 'sales:edit' pk=instance.pk %}" class="btn btn-default btn-icon waves-effect waves-circle waves-float"><i class="zmdi zmdi-edit"></i></a>
                                	<a data-id="{{instance.pk}}" href="{% url 'sales:delete' pk=instance.pk %}" data-text="{{confirm_delete_message}}" data-title="Are you sure?" class="action-button remove btn btn-default btn-icon waves-effect waves-circle waves-float"><i class="zmdi zmdi-delete"></i></a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>

                <!--pagination -->
                <div class="bootgrid-footer container-fluid" id="data-table-selection-footer">
                	{% get_pages %}
                	<div class="row">
                		<div class="col-sm-6">
                			<div class="pagination">
                				{% show_pages %}
                			</div>
                		</div>
                		<div class="col-sm-6 infoBar">
                			<div class="infos">
                				Showing {{title}} <span class="current_page_index">{{ pages.current_start_index }}</span> - <span class="current_end_status">{{ pages.current_end_index }}</span> of <span class="total_count">{{ pages.total_count }}</span>
                			</div>
                		</div>
                	</div>
                </div>
                <!--pagination-->
                {% else %}
                	{% include 'includes/not_found.html' %}
                {% endif %}
            </div>

        </div>
    </section>
{% endblock %}

{% block filter_box %}
<div class="filter-box">
	 <form method="get" action="{% url 'sales:sales' %}">
	 	<div class="card">
			<div class="card-header">
		        <h2>Filter <small></small></h2>
		        <span class="back-button-poupup palette-Cyan bg white btn btn-default btn-icon-text waves-effect"><i class="zmdi zmdi-arrow-back"></i> Back</span>
		    </div>

			<div class="card-body card-padding">
			 	<div class="form-group fg-line">
		            <label>Query</label>
		            <input name="q" type="text" class="form-control" placeholder="Enter your query..." />
		        </div>

		         <div class="m-t-20">
                    <button type="submit" class="btn btn-info waves-effect">Submit</button>
                </div>
		    </div>
		 </div>
	 </form>
</div>
{% endblock %}

{% block static %}
	{% load static %}
{% endblock %}